// File generated by FlutterFire CLI, do not edit directly.

import 'package:alice/config.dart';
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

AppConfig appConfig = AppConfig();

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: appConfig.firebaseAndroidApiKey,
    appId: appConfig.firebaseAndroidAppId,
    messagingSenderId: appConfig.firebaseMessagingSenderId,
    projectId: appConfig.firebaseProjectId,
    storageBucket: appConfig.firebaseStorageBucket,
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: appConfig.firebaseIosApiKey,
    appId: appConfig.firebaseIosAppId,
    messagingSenderId: appConfig.firebaseMessagingSenderId,
    projectId: appConfig.firebaseProjectId,
    storageBucket: appConfig.firebaseStorageBucket,
    androidClientId: appConfig.firebaseAndroidClientId,
    iosClientId: appConfig.firebaseIosClientId,
    iosBundleId: appConfig.firebaseIosBundleId,
  );
}