name: 📱 Mobile Release
on:
  workflow_dispatch:
    inputs:
      release_version:
        description: "Release version (format: x.x.x+y)"
        required: true
permissions:
  contents: write
jobs:
  release:
    name: Build and Release iOS to TestFlight
    runs-on: macos-14
    timeout-minutes: 60
    steps:
      - name: ⬇️ Checkout code
        uses: actions/checkout@v4
      - name: 💾 Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.38.5'
      - name: 🧪 Validate version format
        run: |
          echo "Release version: ${{ github.event.inputs.release_version }}"
          if [[ ! "${{ github.event.inputs.release_version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+\+[0-9]+$ ]]; then
            echo "❌ Invalid version format. Must be x.x.x+y (e.g. 1.2.3+4)"
            exit 1
          fi
      - name: 🧪 Extract version and build number
        run: |
          version="${{ github.event.inputs.release_version }}" # x.x.x+y
          version_part="${version%%+*}" # Extracts x.x.x
          build_number="${version#*+}" # Extracts y
          echo "Version: $version_part"
          echo "Build Number: $build_number"
          echo "VERSION=$version_part" >> $GITHUB_ENV
          echo "BUILD_NUMBER=$build_number" >> $GITHUB_ENV
          echo "ENVIRONMENT=Dev" >> $GITHUB_ENV
          
      - name: 🔧 Update pubspec.yaml version
        run: |
          version="${{ github.event.inputs.release_version }}"
          sed -i "" "s/^version: .*/version: $version/" pubspec.yaml
          echo "✅ pubspec.yaml updated to version: $version"

      - name: 🔐 Create .env file from secret (Dev)
        run: |

          if [ -z "${{ secrets.FLUTTER_ENV_DEV_BASE64 }}" ]; then
            echo "❌ FLUTTER_ENV_DEV_BASE64 secret is not set."
            exit 1
          fi
          echo "${{ secrets.FLUTTER_ENV_DEV_BASE64 }}" | base64 --decode > .env
          echo "✅ .env file created for development environment"

      - name: 📂 Create google json key file from secret (Dev)
        run: |
          if [ -z "${{ secrets.GOOGLE_SERVICE_JSON_DEV_BASE64 }}" ]; then
            echo "❌ GOOGLE_SERVICE_JSON_DEV_BASE64 secret is not set."
            exit 1
          fi
          echo "${{ secrets.GOOGLE_SERVICE_JSON_DEV_BASE64 }}" | base64 --decode > android/app/google-services.json
          echo "✅ google-services.json file created for development environment"

      # -------- ANDROID STEPS -------- #

      - name: 🧱 Decode keystore from base64
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/release-key.jks
      - name: 🧪 Update release keystore values in key.properties
        run: |
          store_pass="${{ secrets.ANDROID_KEYSTORE_PASSWORD }}"
          key_pass="${{ secrets.ANDROID_KEY_PASSWORD }}"
          key_alias="${{ secrets.ANDROID_KEY_ALIAS }}"
          store_file="release-key.jks"
      
          if [[ "$store_pass" == "none" ]]; then store_pass=""; fi
          if [[ "$key_pass" == "none" ]]; then key_pass=""; fi
          if [ ! -f android/key.properties ]; then
          touch android/key.properties
          fi 

          set_key() {
            key="$1"
            value="$2"
            if grep -q "^$key=" android/key.properties; then
              sed -i'' -e "s|^$key=.*|$key=$value|" android/key.properties
            else
              echo "$key=$value" >> android/key.properties
            fi
          }  

          set_key "StorePassword" "$store_pass"
          set_key "KeyPassword" "$key_pass"
          set_key "KeyAlias" "$key_alias"
          set_key "StoreFile" "$store_file"
      - name: 🔧 Update Android version and build number in build.gradle
        run: |
          version="${{ env.VERSION }}"
          build_number="${{ env.BUILD_NUMBER }}"
      
          sed -i '' "s/versionCode flutter.versionCode/versionCode $build_number/" android/app/build.gradle
          sed -i '' "s/versionName flutter.versionName/versionName \"$version\"/" android/app/build.gradle

          echo "✅ Android build.gradle updated with versionName $version and versionCode $build_number"


      - name: 🔨 Build signed Android APK
        run: |
          flutter build apk --release
          
      - name: 🚀 Upload to Firebase App Distribution (CLI)
        run: |
          curl -sL https://firebase.tools | bash
            firebase appdistribution:distribute build/app/outputs/flutter-apk/app-release.apk \
            --app "${{ secrets.FIREBASE_APP_ID_DEV }}" \
            --token "${{ secrets.FIREBASE_CLI_TOKEN }}" \
            --groups "BlueSkyAi"


      #       # -------- FINAL: TAG & RELEASE --------

            
      - name: 🧹 Clean up API key
        run: rm ios/AuthKey.p8 || true
      - name: 🏷️ Tag the release
        run: |
          git config --global user.name "Sebastian Vasquez"
          git config --global user.email "sebastian@blueskyai.co"
          git fetch --prune --unshallow

          git tag "v${{ github.event.inputs.release_version }}-${{env.ENVIRONMENT}}"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} --tags
      - name: 📰 Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "v${{ github.event.inputs.release_version }}-${{env.ENVIRONMENT}}"
          generate_release_notes: true
      - name: 🧾 Upload Xcode build logs if build fails
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: xcode-build-log
          path: ~/Library/Logs/gym/