final List<Map<String, dynamic>> dummyAdds = [
  {
    'addId': '12345',
    'liked': 10,
    'title': 'one two tree',
    'description': 'This is a sample add description.',
    'tags': ['tag1', 'tag2', 'tag3'],
    'images': ['image1.jpg', 'image2.jpg'],
    'createdAt': DateTime.now().toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'addId': '67890',
    'liked': 25,
    'title': 'Second Add',
    'description': 'Another add for testing.',
    'tags': ['tag2', 'tag4'],
    'images': ['image3.jpg'],
    'createdAt': DateTime.now().subtract(Duration(days: 1)).toIso8601String(),
    'updatedAt': DateTime.now().toIso8601String(),
  },
  {
    'addId': '54321',
    'liked': 5,
    'title': 'Third Add',
    'description': 'Yet another add example.',
    'tags': ['tag1'],
    'images': ['image4.jpg', 'image5.jpg', 'image6.jpg'],
    'createdAt': DateTime.now().subtract(Duration(days: 2)).toIso8601String(),
    'updatedAt': DateTime.now().subtract(Duration(days: 1)).toIso8601String(),
  },
  {
    'addId': '11223',
    'liked': 17,
    'title': 'Fourth Add',
    'description': 'A fourth mock add for demo.',
    'tags': ['tag3', 'tag5'],
    'images': ['image7.jpg'],
    'createdAt': DateTime.now().subtract(Duration(days: 3)).toIso8601String(),
    'updatedAt': DateTime.now().subtract(Duration(days: 2)).toIso8601String(),
  },
  {
    'addId': '99999',
    'liked': 30,
    'title': 'Fifth Add',
    'description': 'A fifth mock add for testing.',
    'tags': ['tag6'],
    'images': ['image8.jpg'],
    'createdAt': DateTime.now().subtract(Duration(days: 4)).toIso8601String(),
    'updatedAt': DateTime.now().subtract(Duration(days: 3)).toIso8601String(),
  },
  {
    'addId': '88888',
    'liked': 12,
    'title': 'Sixth Add',
    'description': 'A sixth mock add for demonstration.',
    'tags': ['tag7', 'tag8'],
    'images': ['image9.jpg', 'image10.jpg'],
    'createdAt': DateTime.now().subtract(Duration(days: 5)).toIso8601String(),
    'updatedAt': DateTime.now().subtract(Duration(days: 4)).toIso8601String(),
  },
];