
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    avoid_returning_null: true
    avoid_shadowing_type_parameters: true
    always_declare_return_types: true
    always_use_package_imports: true
    prefer_const_constructors: true
    avoid_unused_constructor_parameters: true
    avoid_empty_else: true
    prefer_final_locals: true
    unnecessary_new: true
    unnecessary_this: true
    directives_ordering: true
    sort_pub_dependencies: true
    prefer_single_quotes: true
    prefer_interpolation_to_compose_strings: true
    prefer_expression_function_bodies: true
    avoid_types_on_closure_parameters: true
    avoid_init_to_null: true
    unnecessary_late: true
    empty_catches: true
    empty_constructor_bodies: true
    avoid_unnecessary_containers: false
    use_build_context_synchronously: true
    unnecessary_getters_setters: false

analyzer:
  exclude:
     - "**/*.g.dart"
     - "**/*.freezed.dart"
     - "**/*.mocks.dart"
     - "android/**"
     - "ios/**"
